# 线上配置文件
# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
#  profiles:
#    active: prod
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yourdata
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
        secure: false
        same-site: lax

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
aliyun:
  oss:
    endpoint: your endpoint
    accessKeyId: your accessKeyId
    accessKeySecret: your accessKeySecret
    bucketName: your bucketName
